### ISSUE TITLE
Research the router export

### ISSUE THREAD

**Issue by abdonrd** [IBM/pwa-lit-template#10]
Right now we lazy import and initialize the router here:

https://github.com/IBM/pwa-lit-template/blob/5fb2c633276bf0b4bdcc339d9a3c7f1f988a0359/src/components/app-index.ts#L81-L89

This `router.init()` function doesn't export anything:

https://github.com/IBM/pwa-lit-template/blob/5fb2c633276bf0b4bdcc339d9a3c7f1f988a0359/src/router/index.ts#L13-L27

Doing it this way, we found a problem:
**We can't import the router instance to use the router helpers**.

For example, we want to replace the hardcoded link in the not found page to use the router name. From this:

https://github.com/IBM/pwa-lit-template/blob/5fb2c633276bf0b4bdcc339d9a3c7f1f988a0359/src/pages/page-not-found.ts#L29

To something like this:

```html
<a href="${router.urlForName('home')}">Back to home</a> 
```

And the same for the navigation links:

https://github.com/IBM/pwa-lit-template/blob/5fb2c633276bf0b4bdcc339d9a3c7f1f988a0359/src/components/app-index.ts#L57-L61

**Comment by abdonrd** [comment]
A proposal: https://github.com/IBM/pwa-lit-template/pull/20

**Comment by abdonrd** [comment]
This is also important to inherit the `baseUrl` property from the Vaadin Router in the routes.

**Comment by web-padawan** [comment]
I would consider using async directive for `urlForName` helpers. 

```js
let routerInstance;

export const initRouter = async (outlet) => {
  if (!routerInstance && outlet) {
    const router = await import('../router/index');
    routerInstance = router.init(outlet);
  }
  return routerInstance;
};

export const waitForRouter = () => {
  return new Promise((resolve) => {
    if (routerInstance) {
      resolve(routerInstance);
    } else {
      setTimeout(() => waitForRouter(), 100);
    }
  });
};

// use "until" directive to use helpers asynchronously
export const urlForName = (name) => {
  return until(waitForRouter().then((r) => r.urlForName(name)), '');
};
```

**Comment by abdonrd** [comment]
Thanks @web-padawan! 👏

I will try it as soon as I can! (busy days 😅 )

**Comment by abdonrd** [comment]
@web-padawan I'm missing something, right? Because I have not managed to make it work.

You can see it here: https://github.com/IBM/pwa-lit-template/compare/router-helper

**Comment by web-padawan** [comment]
I will experiment with your branch later today, and will try to come up with a better approach.

**Comment by web-padawan** [comment]
Submitted a PR with a proposed change: https://github.com/IBM/pwa-lit-template/pull/64
