### ISSUE TITLE
Setup Renovate to test and merge minor and patch releases without PR

### ISSUE THREAD

**Issue by abdonrd** [IBM/pwa-lit-template#438]
We want to try setup Renovate to test and merge minor and patch releases without PR.

Current config:

https://github.com/IBM/pwa-lit-template/blob/de1f2057963445aaa9f9da5e4f889fbfa2cad9fc/.github/renovate.json#L1-L22

**Comment by stephenwade** [comment]
I'd be happy to help! Do you want pull requests opened and automatically merged for every update, or do you want to quietly merge anything that passes CI?

https://docs.renovatebot.com/automerge-configuration/#branch-vs-pr-automerging
