### ISSUE TITLE
When running npm run build I get errors

### ISSUE THREAD

**Issue by saado-n** [IBM/pwa-lit-template#491]
#### Describe the bug

[!] Error: ENOENT: no such file or directory, lstat 'C:\Users\saadon\AppData\Local\Temp\6'

#### To reproduce

Type npm run build 

#### Expected behavior

I am interested to build for different env (CI, QA, EA and PRD), and each build should use the relevant config file (config.ci.ts, config.qa.ts etc.).

Thank you

**Comment by saado-n** [comment]
I added a folder name `6` in the `TEMP` file and the build succeed.
But now I have a lot of JS files inside the `dist` folder.

I assuming that now I need to:

1. concatenate them into one JS file.
2. Go to the shell app and add the `<app-index id="appIndex"></app-index>` and then import the concatenate JS file.

Is that right?

**Comment by abdonrd** [comment]
I cannot reproduce this error.
Describe in detail how to reproduce it. Thanks!

**Comment by saado-n** [comment]
I used this Lit template:
https://github.com/ibm/pwa-lit-template
When running npm run build`
The dist folder contains a lot of files and not one JS file:
From this thread, I understand that I do not need the nomodule-* files.
What about the pollyfills ?
Since Rollup not bundles the content into one file, I am doing this:

const fs = require('fs-extra');
const concat = require('concat');
(async function build() {
    const files = [
        './dist/polyfills/core-js.e929db2b8035152f0c914099d204ebdb.js',
        './dist/polyfills/custom-elements-es5-adapter.3342b468203af1a14ca005e80d14148f.js',
        './dist/polyfills/fetch.c406ed8f3fd5c584ab4b8ee2407c3814.js',
        './dist/polyfills/lit-polyfill-support.82aa27f27be323af5a455ac87919622a.js',
        './dist/polyfills/systemjs.200c680897e2c47082fe1714c434a7c3.js',
        './dist/polyfills/webcomponents.d7ffce1754011cfedff5f846f12e0c11.js',
        './dist/3e65f965.js',
        './dist/5c8a6e57.js',
        './dist/5e4975e3.js',
        './dist/7a605035.js',
        './dist/7390d4e5.js',
        './dist/fbb70b96.js',
        './dist/index.html',
        './dist/manifest.webmanifest',
        './dist/nomodule-0aae2f84.js',
        './dist/nomodule-78c1e4c3.js',
        './dist/nomodule-23591c4a.js',
        './dist/nomodule-a817c292.js',
        './dist/nomodule-a921ba44.js',
        './dist/nomodule-a3965611.js',
        './dist/nomodule-c6145fdc.js',
        './dist/robots.txt',
    ]
    await fs.ensureDir('elements');
    await concat(files, './elements/core-dashboard-lit-web-component.js');

    // await fs.copyFile('./dist/sisense-sdk-element/styles.css', './elements/sisense-sdk-element.css');
    // await fs.copy('./dist/sisense-sdk-element/assets/', './elements/assets/');

    await fs.emptyDir('./dist');
    await fs.copy('./elements', './dist');
    
Here is the rollup config file:

import { createSpaConfig } from '@open-wc/building-rollup';
import replace from '@rollup/plugin-replace';
import typescript from '@rollup/plugin-typescript';
import { copy } from '@web/rollup-plugin-copy';
import { black, blue } from 'chalk';
import merge from 'deepmerge';

const NODE_ENV = process.env.NODE_ENV || 'development';
const DIST_PATH = './dist/';
const GENERATE_SERVICE_WORKER = false;

const absoluteBaseUrl =
  NODE_ENV === 'production'
    ? 'https://pwa-lit-template.mybluemix.net'
    : 'http://localhost:8000';

const workboxConfig = {
  sourcemap: false,
  runtimeCaching: [
    {
      urlPattern: /images\/.*$/,
      handler: 'CacheFirst',
      options: {
        cacheName: 'images',
        expiration: {
          maxEntries: 60,
          maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
        },
      },
    },
  ],
  skipWaiting: false,
  clientsClaim: false,
};

const config = merge(
  createSpaConfig({
    outputDir: DIST_PATH,
    html: {
      absoluteBaseUrl,
      extractAssets: false,
    },
    legacyBuild: true,
    polyfillsLoader: {
      polyfills: {
        custom: [
          {
            name: 'lit-polyfill-support',
            path: 'node_modules/lit/polyfill-support.js',
            test: "!('attachShadow' in Element.prototype)",
            module: false,
          },
        ],
      },
    },
    developmentMode: process.env.ROLLUP_WATCH === 'true',
    workbox: GENERATE_SERVICE_WORKER && workboxConfig,
    injectServiceWorker: GENERATE_SERVICE_WORKER,
  }),
  {
    input: 'index.html',
    plugins: [
      typescript({
        declaration: false,
        sourceMap: false,
        inlineSources: false,
      }),
      replace({
        preventAssignment: true,
        values: {
          'process.env.NODE_ENV': JSON.stringify('production'),
        },
      }),
      ...(NODE_ENV !== 'development'
        ? [
            replace({
              preventAssignment: true,
              include: 'src/**/*.ts',
              exclude: 'src/config.*.ts',
              delimiters: ['', ''],
              values: {
                './config.js': `./config.${NODE_ENV}.js`,
              },
            }),
          ]
        : []),
      copy({
        // Copy all the static files
        patterns: ['images/**/*', 'manifest.webmanifest', 'robots.txt'],
      }),
    ],
  }
);

console.log(`${black.bgWhite(' Build information'.padEnd(60, ' '))}

${blue('Name')}                   ${process.env.npm_package_name}
${blue('Environment')}            ${NODE_ENV}
${blue('Service Worker')}         ${GENERATE_SERVICE_WORKER}
${blue('Version')}                v${process.env.npm_package_version}`);

export default config;

And here is my package-json:

    "build": "rimraf server/dist/ && rollup --config && node concatenate.js",
    "build:ci": "rimraf server/dist/ && rollup --config --environment INCLUDE_DEPS,BUILD:ci && node concatenate.js",
    
What is the best practice to generate 1 JS file without publishing it into npm as a package?

Eventually, I am interested to use the WC like this:
<script type="module" src="/lib/components/my-elements.js">
<my-element></my-element>

**Comment by saado-n** [comment]
When I trying to use the WC inside a simple JS app like this:
```
<!DOCTYPE HTML>
<html>

<body>
  <script>
    console.log("App is running");
  </script>

<app-index id="appIndex"></app-index>
  <!-- <script>
    const a = document.querySelector("app-index");
    a.setAttribute("token", "No Token");
  </script> -->
  <script type="module" src="./elements/core-dashboard-lit-web-component.js"></script>
</body>

</html>
```
I get:
```
Access to script at 'file:///C:/Repositories/UI/Hello%20World/elements/core-dashboard-lit-web-component.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
index.html:14 GET file:///C:/Repositories/UI/Hello%20World/elements/core-dashboard-lit-web-component.js net::ERR_FAILED
```

**Comment by abdonrd** [comment]
I just see you move it to a new discussion here:
https://github.com/IBM/pwa-lit-template/discussions/493
