### ISSUE TITLE
Expected router outlet to be a valid DOM Node

### ISSUE THREAD

**Issue by y2us** [IBM/pwa-lit-template#512]
On Firefox Ubuntu

I use npm start and then the content doesn't appear, only the menu.

Uncaught (in promise) TypeError: [Vaadin.Router] Expected router outlet to be a valid DOM Node (but got undefined)
    __ensureOutlet router.js:752
    __addAppearingContent router.js:786
    ready router.js:498
    promise callback*render router.js:469
    attachRouter index.ts:29
    firstUpdated app-index.ts:103
    _$didUpdate reactive-element.ts:1350
    performUpdate reactive-element.ts:1317
    scheduleUpdate reactive-element.ts:1235
    __enqueueUpdate reactive-element.ts:1207
    requestUpdate reactive-element.ts:1182
    _initialize reactive-element.ts:924
    ReactiveElement reactive-element.ts:907
    LitElement lit-element.js:82
    AppIndex app-index.ts:18
    legacyCustomElement custom-element.ts:21
    customElement custom-element.ts:64
    __decorateClass app-index.ts:7
    <anonymous> app-index.ts:18
[router.js:752:12](http://192.168.1.108:8000/node_modules/@vaadin/router/src/router.js)
GEThttp://192.168.1.108:8000/src/pages/page-about.ts
[[HTTP/1.1 304 Not Modified 1ms]]()

**Comment by abdonrd** [comment]
Sorry for the late response!
Looks like there is an issue in the latest `@web/dev-server-esbuild`.
PR fixing it: https://github.com/IBM/pwa-lit-template/pull/516
